import { emitAppEvent } from './common/app-events.js?v=app-20261010-17';
import { createIndexedDbAdapter } from './indexeddb-adapter.js?v=app-20261010-17';

const adapter = createIndexedDbAdapter({ databaseName: 'hallapa_db', emitAppEvent });
export const {
  ensureDefaultCashflowMasters,
  getTransactions,
  addTransaction,
  updateTransaction,
  deleteTransaction,
  clearAllTransactions,
  getUsers,
  addUser,
  getCustomers,
  addCustomer,
  updateCustomer,
  deleteCustomer,
  bulkInsertCustomers,
  bulkReplaceCustomerTypes,
  bulkReplaceCustomerGroups,
  getCustomerTypes,
  addCustomerType,
  updateCustomerType,
  deleteCustomerType,
  getCustomerGroups,
  addCustomerGroup,
  updateCustomerGroup,
  deleteCustomerGroup,
  renameCustomerTypeNameEverywhere,
  renameCustomerGroupNameEverywhere,
  getItems,
  addItemMaster,
  updateItem,
  renameItem,
  deleteItem,
  bulkInsertItems,
  bulkReplaceItemGroups,
  getItemGroups,
  addItemGroup,
  updateItemGroup,
  deleteItemGroup,
  renameItemGroupNameInItems,
  getCashflowTypes,
  addCashflowType,
  updateCashflowType,
  deleteCashflowType,
  bulkReplaceCashflowTypes,
  getCashflowItems,
  addCashflowItem,
  updateCashflowItem,
  deleteCashflowItem,
  bulkReplaceCashflowItems,
  getCashflowGroups,
  addCashflowGroup,
  updateCashflowGroup,
  deleteCashflowGroup,
  bulkReplaceCashflowGroups,
  getAllLedgerTx,
  putLedgerTx,
  getLedgerTxById,
  deleteLedgerTxById,
  clearAllLedgerTx,
  migrateLegacyLedgerTxIfNeeded,
  ensureCashflowMastersIfEmpty,
  exportHallapaDbSnapshot,
  restoreHallapaDbSnapshot,
} = adapter;
